name: Build Jekyll artifact

on:
  push:
    branches: ["main"]
      when:
        paths:
          - "src/**"
          - ".github/workflows/jekyll.yml"
  workflow_dispatch:

jobs:
  - name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v1
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler: true
        bundler-cache: true
    - name: Jekyll build
      run: bundle exec jekyll build
    - name: Commit artifact
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        add: 'src/_site'
        default_author: github-actions
        message: 'Build Jekyll site'
